<table>
    <?php if ($object->title()): ?>
        <caption><?php echo $object->title() ?></caption>
    <?php endif ?>
    <thead>
        <?php foreach ($object->columnNames() as $columnName): ?>
            <th><?php echo $columnName ?></th>
        <?php endforeach ?>
    </thead>
    <tbody>
        <?php foreach ($object->rows() as $row): ?>
            <?php echo $this->render($row) ?>
        <?php endforeach ?>
    </tbody>
</table>
