<table class="table table-striped">
    <?php if ($object->title()): ?>
        <caption><?php echo $object->title() ?></caption>
    <?php endif ?>
    <?php if ($object->headers()): ?>
        <thead class="thead-light">
         
            <?php foreach ($object->headers() as $header): ?>
                <th><?php echo $header ?></th>
            <?php endforeach ?>
        </thead>
    <?php endif ?>
    <tbody>
        <?php foreach ($object->rows() as $row): ?>
            <?php echo $this->render($row) ?>
        <?php endforeach ?>
    </tbody>
</table>
