<span style="color: #<?php 

use PhpBench\Expression\Ast\RelativeDeviationNode;
use PhpBench\Expression\Theme\Util\Color;
use PhpBench\Expression\Theme\Util\Gradient;

assert($object instanceof RelativeDeviationNode); 
echo Gradient::start(
    Color::fromHex('#000000')
)->to(
    Color::fromHex('#ff0000'), 100
)->colorAtPercentile(0 +(int)$object->value())->toHex();
?>"><?php echo $this->nodePrinter->print($object) ?></span>

